# Generated by Django 5.1.6 on 2025-02-17 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wandercritic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50, unique=True)),
                ('about', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=300)),
                ('seasons', models.CharField(max_length=30)),
                ('activity', models.CharField(max_length=30)),
                ('travel_theme', models.CharField(max_length=30)),
                ('budget', models.IntegerField(default=0)),
                ('reviews', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=30)),
                ('rate', models.IntegerField(default=5)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50, unique=True)),
                ('information', models.CharField(max_length=128)),
                ('picture', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wandercritic.place')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
